server:
  port: 8081
secure_store: ephemeral
secure_store_props: src/main/resources/ephemeral.properties
spring:
  application:
    name: edge-dcb
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,loggers
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
folio:
  tenant:
    validation:
      enabled: false
  system-user:
    username: system-user
  environment: folio
  okapi-url: ${okapi_url:http://okapi:9130}
logging:
  level:
    org:
      springframework:
        cache: OFF
