server:
  port: 8081
secure_store: ephemeral
secure_store_props: src/main/resources/ephemeral.properties
okapi_url: http://localhost:9130
spring:
  application:
    name: edge-dcb
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: ${ACTUATOR_EXPOSURE:health,info,loggers}
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
folio:
  tenant:
    validation:
      enabled: false
  system-user:
    username: system-user
    password: ${SYSTEM_USER_PASSWORD} # This is not used but added to avoid DI errors from folio-spring-system-user
  environment: folio
logging:
  level:
    org:
      springframework:
        cache: OFF
