Dokapi_url: http://localhost:9130
okapi_url: ${Dokapi_url}
Dsecure_store_props: src/main/resources/ephemeral.properties
secure_store_props: ${Dsecure_store_props}
Dsecure_store: Ephemeral
secure_store: ${Dsecure_store}
Dcaia_soft_client: caiaSoftClient
caia_soft_client: ${Dcaia_soft_client}
Dcaia_soft_tenants: caiaSoftClient_tenants
caia_soft_tenants: ${Dcaia_soft_tenants}
spring:
  application:
    name: edge-dcb
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,loggers
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF
server.port: 8081
folio.tenant.validation.enabled: false

# configurations update timeframe (millis)
configurations.update.timeframe: 3600000
