Dokapi_url: http://localhost:9130
okapi_url: ${Dokapi_url}
spring:
  application:
    name: edge-dcb
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false
  flyway:
    enabled: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health,info,loggers
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: full
folio:
  system-user:
    username: system-user
  environment: folio
  okapi_url: ${Dokapi_url}
logging:
  level:
    org:
      springframework:
        cache: OFF
server.port: 8081
folio.tenant.validation.enabled: false

# configurations update timeframe (millis)
configurations.update.timeframe: 3600000
