openapi: 3.0.3
info:
  title: Edge DCB FOLIO API
  description: Edge DCB FOLIO API
  version: 1.0.0
servers:
  - url: /dcbService/
paths:
  /transactions/{dcbTransactionId}:
    post:
      summary: Create DCB transaction request
      operationId: createDCBTransaction
      tags:
        - circulation
      parameters:
        - $ref: '#/components/parameters/dcbTransactionId'
      requestBody:
        $ref: "#/components/requestBodies/DCBTransaction"
      responses:
        '201':
          $ref: '#/components/responses/TransactionStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /transactions/{dcbTransactionId}/status:
    parameters:
      - $ref: '#/components/parameters/dcbTransactionId'
    get:
      description: Get transaction status across circulation institutions
      operationId: getDCBTransactionStatusById
      tags:
        - circulation
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      description: Update transaction status across circulation institutions
      operationId: updateDCBTransactionStatus
      tags:
        - circulation
      requestBody:
        $ref: '#/components/requestBodies/TransactionStatusBody'
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  requestBodies:
    TransactionStatusBody:
      description: TransactionStatus object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    DCBTransaction:
      description: DCB transaction object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/dcbTransaction.yaml#/DcbTransaction"
  responses:
    TransactionStatus:
      description: Transaction Status object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    TransactionStatusResponse:
      description: TransactionStatusResponse object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatusResponse.yaml#/TransactionStatusResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    dcbTransactionId:
      in: path
      name: dcbTransactionId
      schema:
        type: string
      required: true
