openapi: 3.0.0
info:
  title: Edge CasiaSoft API
  version: v1
servers:
  - url: /caiasoftService/
paths:
  /ItemBarcodes/{itemBarcode}/accessioned/{remoteStorageConfigurationId}:
    get:
      responses:
        '200':
          description: Success get accession item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/accessionItem"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      operationId: getAccessionItem
      parameters:
        - $ref: "#/components/parameters/item-barcode"
        - $ref: "#/components/parameters/remote-storage-id"
        - $ref: "#/components/parameters/x-okapi-token"
        - $ref: "#/components/parameters/x-okapi-tenant"
  /RequestBarcodes/{itemBarcode}/reshelved/{remoteStorageConfigurationId}:
    post:
      responses:
        '201':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/returnItemResponse"
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Perform item return
      operationId: returnItemByBarcode
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: false
      parameters:
        - $ref: "#/components/parameters/item-barcode"
        - $ref: "#/components/parameters/remote-storage-id"
        - $ref: "#/components/parameters/x-okapi-token"
        - $ref: "#/components/parameters/x-okapi-tenant"
  /Requests/{requestId}/route/{remoteStorageConfigurationId}:
     post:
       responses:
         '200':
           description: Success check-in by requestId and remoteStorageConfigurationId
           content:
             text/plain:
               schema:
                 type: string
         '500':
           description: Internal server error
           content:
             text/plain:
               schema:
                 type: string
                 example: Internal server error
       operationId: checkInByHoldId
       parameters:
         - $ref: "#/components/parameters/request-id"
         - $ref: "#/components/parameters/remote-storage-id"
         - $ref: "#/components/parameters/x-okapi-token"
         - $ref: "#/components/parameters/x-okapi-tenant"
  /Transactions/{dcbTransactionId}/status:
    parameters:
      - in: path
        name: dcbTransactionId
        description: The ReShare DCB ID for the transaction being brokered.
        schema:
          type: string
      - $ref: "#/components/parameters/x-okapi-token"
      - $ref: "#/components/parameters/x-okapi-tenant"
    get:
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionStatusResponse'
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      operationId: getDcbTransactionStatus
components:
  schemas:
    accessionItem:
      $ref: schemas/accessionItem.json
    accessionQueues:
      allOf:
        - type: object
          properties:
            accessions:
              type: array
              items:
                $ref: "#/components/schemas/accessionItem"
    checkInItem:
      $ref: schemas/checkInItem.json
    returnItemResponse:
      $ref: schemas/returnItemResponse.json
    TransactionStatus:
      type: object
      properties:
        status:
          type: string
          enum:
            - CREATED #Created by DCB
            - OPEN #Created in lending library, Item is available
            - CANCELLED #Request canceled by lending library or patron
            - IN_TRANSIT #checked in at another service point
            - AWAITING_PICKUP #checked in at the same service point. Item status should change from "Checked out" to "Awaiting pickup"
            - ITEM_CHECKED_OUT #Request is fulfilled and loan is created, Item checkout by patron
            - ITEM_CHECKED_IN #Item returned to pickup location
            - IN_TRANSIT_TO_LENDING #Item in transit from pickup location to owning library
            - CLOSED #Item returned to lending library
            - ERROR #General error
        message:
          type: string
    TransactionStatusResponse:
        allOf:
          - $ref: '#/components/schemas/TransactionStatus'
          - type: object
            properties:
              item:
                $ref: '#/components/schemas/DCBItem'
              patron:
                $ref: '#/components/schemas/DCBPatron'
    DCBItem:
        description: Item metadata required for the transaction
        type: object
        properties:
          itemUUID:
            description: The unique item identifier as known to ReShare DCB
            type: string
            format: uuid
          itemTitle:
            description: The title of the item that has been requested
            type: string
          itemBarcode:
            description: The barcode of the item as specified in the lending library
            type: string
          pickupLocation:
            description: The code in ReShare DCB which identifies the pickup library
            type: string
          dcbMaterialType:
            description: The “hub-normalized” form of the item item type, used in the circulation rules for determining the correct loan policy.
            type: string
          dcbLendingLibraryCode:
            description: The code in ReShare DCB which identifies the lending library
            type: string
          dcbTransactionId:
            description: The ReShare DCB ID for the transaction being brokered.
            type: string

    DCBPatron:
        description: Patron metadata required for the transaction
        type: object
        properties:
          patronUUID:
            description: The unique identifier for the patron making the request as known in the requesting library
            type: string
            format: uuid
          dcbPatronGroup:
            description: The patron group associated with the requesting patron as found in ReShare DCB
            type: string
          dcbPatronBarcode:
            description: The barcode of the patron as found in ReShare DCB
            type: string
          dcbBorrowingLibraryCode:
            description: The code in ReShare DCB which identifies the borrowing library
            type: string
          dcbTransactionId:
            description: The ReShare DCB ID for the transaction being brokered.
            type: string

  parameters:
    item-barcode:
      name: itemBarcode
      in: path
      required: true
      schema:
        type: string
    remote-storage-id:
      name: remoteStorageConfigurationId
      in: path
      required: true
      schema:
        $ref: schemas/uuid.json
    request-id:
      name: requestId
      in: path
      required: true
      schema:
        type: string
    x-okapi-token:
      name: x-okapi-token
      in: header
      required: true
      schema:
        type: string
    x-okapi-tenant:
      name: x-okapi-tenant
      in: header
      required: true
      schema:
        type: string
