openapi: 3.0.0
info:
  title: Edge DCB API
  version: 0.0.1
servers:
  - url: /dcbService/
paths:
  /transactions/{dcbTransactionId}:
    post:
      summary: Create DCB transaction request
      operationId: createDCBTransaction
      parameters:
        - $ref: '#/components/parameters/dcbTransactionId'
      tags:
        - circulation
      responses:
        '201':
          $ref: '#/components/responses/TransactionStatus'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        $ref: "#/components/requestBodies/DCBObject"
  /transactions/{dcbTransactionId}/status:
    get:
      summary: Get transaction status across circulation institutions
      operationId: getDCBTransactionStatus
      parameters:
        - $ref: '#/components/parameters/dcbTransactionId'
      tags:
        - circulation
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update transaction status across circulation institutions
      operationId: updateDCBTransactionStatus
      tags:
        - circulation
      parameters:
        - $ref: '#/components/parameters/dcbTransactionId'
      responses:
        '200':
          $ref: '#/components/responses/TransactionStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        $ref: '#/components/requestBodies/TransactionStatusBody'
components:
  requestBodies:
    TransactionStatusBody:
      description: Transaction Status object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    DCBObject:
      description: DCBItem object
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              DCBItem:
                $ref: 'schemas/dcbItem.yaml'
              DCBPatron:
                $ref: 'schemas/dcbPatron.yaml'

  responses:
    TransactionStatus:
      description: Transaction Status object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatus.yaml#/TransactionStatus"
    TransactionStatusResponse:
      description: TransactionStatusResponse object
      content:
        application/json:
          schema:
            $ref: "schemas/transactionStatusResponse.yaml#/TransactionStatusResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    dcbTransactionId:
      in: path
      name: dcbTransactionId
      schema:
        type: string
      required: true

